### ISSUE TITLE
Initial requirements for the project

### ISSUE THREAD

**Issue by flaviostutz** [sergioflores-j/nn-debugging-interview#1]
What we want to verify:
  - The candidate is able to:
     - Identify that a issue is happening by reading test results
     - Plan an approach for fixing the bug
     - See variable values during debugging
     - Identify logic errors
     - Identify typos
     - Follow other's code logic
     - Implement a working solution for the issues found
     - Handle unknown third part modules (by reading its documentation, or playing with the interface etc)

Overal design:
   - NodeJS with Express based API
   - In memory state store
   - Simple Cache
   - Vanilla JS

TODO service:
   - Create TODO
   - Update TODO
   - List TODO
   - Get TODO
   - Delete TODO

Bugs:
  - Update updates another item in database (typo in ids)
  - Delete item is removing ALL items from memory
  - After deleting an item, GET list continues returning it, but not in GET item (cache invalidation bug)
  - Bonus (hidden bug not caught by unit tests): All TODO titles are stored with the same fixed string "todoTitle" (typo)

We can copy code from https://github.com/haidarrifki/nodejs-todo-app and change it

**Comment by flaviostutz** [comment]
Use code sandbox to avoid struggles with machine environment

**Comment by sergioflores-j** [comment]
The problem: https://demo.hedgedoc.org/s/B14kxcYgv

**Comment by flaviostutz** [comment]
Let's simplify. No Frameworks, no API etc. Vanilla simple code in code sandboxes

**Comment by ckuijjer** [comment]
See https://github.com/ckuijjer/hello-movie-title for the movie title case example, with 3 out of 4 testcases failing
